version: '3.7'

services:
  bot:
    build:
      context: .
    command: ["python", "manage.py", "runserver", "-host=0.0.0.0"]
    depends_on:
      - postgres
    env_file: .env
    environment:
        DATABASE_URL: postgres://postgres@postgres/rmw
    ports:
      - '5000:5000'
    volumes:
      - .:/opt/rmw

  postgres:
    image: postgres:10.7-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/seeds:/docker-entrypoint-initdb.d/
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
