"""empty message

Revision ID: 687fd6cac21f
Revises: 5962ef4cce03
Create Date: 2019-05-01 00:47:53.339115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "687fd6cac21f"
down_revision = "5962ef4cce03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ride_riders", sa.Column("isActive", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ride_riders", "isActive")
    # ### end Alembic commands ###
