"""empty message

Revision ID: 6c9ada82ff09
Revises: 687fd6cac21f
Create Date: 2019-05-13 11:33:52.067318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6c9ada82ff09"
down_revision = "687fd6cac21f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ride_riders", "isActive", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.drop_column("rides", "seats_left")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rides",
        sa.Column("seats_left", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "ride_riders", "isActive", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###
