"""empty message

Revision ID: ba81007cc2e0
Revises: 5002825ba9b0
Create Date: 2018-06-22 15:12:22.951311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba81007cc2e0'
down_revision = '5002825ba9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.alter_column('rides', 'destination',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('rides', 'max_seats',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rides', 'origin',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('rides', 'take_off',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'rides', 'users', ['driver_id'], ['id'])
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'slack_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('users', 'slack_uid',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'slack_uid',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'slack_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.alter_column('rides', 'take_off',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('rides', 'origin',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('rides', 'max_seats',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rides', 'destination',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_column('rides', 'driver_id')
    # ### end Alembic commands ###
