"""empty message

Revision ID: d36c6cda5a72
Revises: 9e93b9838826
Create Date: 2018-06-23 02:00:46.401504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36c6cda5a72'
down_revision = '9e93b9838826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rides', 'users', ['user_id'], ['id'])
    op.create_unique_constraint('unique_constraint_user', 'users', ['slack_uid', 'slack_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_constraint_user', 'users', type_='unique')
    op.drop_constraint(None, 'rides', type_='foreignkey')
    op.drop_column('rides', 'user_id')
    # ### end Alembic commands ###
